// Shared menu content — identical across all 5 themes. Only theming changes.
window.MENU = {
  eyebrow: 'DİJİTAL MENÜ',
  brand: 'KAHVE DÜNYASI',
  branch: 'Bağcılar Keko Şubesi',
  status: 'Açık',
  hero: {
    eyebrow: 'BUGÜN',
    title: 'Yavaş demlenmiş bir öğleden sonra.',
    desc: 'Tek menşeli kahveler, fırından yeni çıkmış hamur işleri ve mevsimlik tabaklar — keten masada servis edilir.',
    img: 'mekan-ic-mekan',
  },
  chefLabel: 'Şefin Seçimi',
  chefNote: 'EL İLE DERLENDİ',
  chefPicks: [
    { name: 'Single Origin Espresso', price: '₺65.00', img: 'espresso' },
    { name: 'Çikolata Fondan', price: '₺120.00', img: 'fondan' },
  ],
  searchPlaceholder: 'Yemek, malzeme veya kategori ara…',
  filters: ['Şefin Seçimi', 'Popüler', 'Yeni'],
  categories: ['Tümü', 'Sıcak İçecekler', 'Soğuk İçecekler', 'Kahvaltı', 'Tatlı'],
  items: [
    { name: 'Single Origin Espresso', price: '₺65.00', cat: 'Sıcak İçecekler', tag: 'Şefin Seçimi', time: '2 dk', img: 'espresso',
      desc: 'Etiyopya\'nın Yirgacheffe bölgesinden, 1.900 metre rakımda yetiştirilen küçük üretici fasulyeleri kendi kavurma atölyemizde orta-açık kavruluyor. Yasemin…' },
    { name: 'Flat White', price: '₺85.00', cat: 'Sıcak İçecekler', tag: 'Popüler', time: '3 dk', img: 'flat-white',
      desc: 'Avustralya usulü, çift shot ristretto üzerine kadifemsi mikro köpük sütü dökerek hazırlanan, yoğun ve dengeli bir kahve.' },
    { name: 'Cold Brew 18h', price: '₺95.00', cat: 'Soğuk İçecekler', tag: 'Yeni', time: '0 dk', img: 'cold-brew',
      desc: '18 saat boyunca soğuk suda demlenen iri öğütülmüş çekirdekler, düşük asitli ve doğal tatlılığı öne çıkan yumuşak bir içim sunar.' },
    { name: 'Tereyağlı Croissant', price: '₺70.00', cat: 'Kahvaltı', tag: null, time: '5 dk', img: 'croissant',
      desc: '72 saatlik soğuk fermantasyonla olgunlaştırılmış hamur, Fransız tereyağıyla kat kat açılır ve her sabah taze pişirilir.' },
    { name: 'Avokado Tost', price: '₺145.00', cat: 'Kahvaltı', tag: 'Popüler', time: '10 dk', img: 'avokado-tost',
      desc: 'Ev yapımı ekşi maya ekmek üzerine olgun avokado püresi, üstüne kaçak yumurta, taze kekik, pul biber ve sızma zeytinyağı.' },
    { name: 'Çikolata Fondan', price: '₺120.00', cat: 'Tatlı', tag: 'Şefin Seçimi', time: '12 dk', img: 'fondan',
      desc: '%70 bitter çikolatadan yapılan, dışı kek dokusunda, içi akışkan sıcak çikolatadan oluşan bir tatlı. Madagaskar vanilyalı dondurma eşliğinde servis…' },
    { name: 'Frenk Üzümü Cheesecake', price: '₺110.00', cat: 'Tatlı', tag: null, time: '5 dk', img: 'cheesecake',
      desc: 'Yoğun ve kremsi New York stili cheesecake, bisküvi tabanı ve ev yapımı kırmızı frenk üzümü kompostosu ile taçlandırılır.' },
  ],
  footer: {
    brand: 'KAHVE DÜNYASI',
    addr: 'testsetset',
    hours: '08.00 - 23.00',
    phone: '5333333333',
    note: 'Fiyatlara KDV dahildir. Alerjen bilgisi için lütfen servis ekibimize danışın.',
    credit: 'EAGLE QR İLE HAZIRLANMIŞTIR',
  },
};
